language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 8.0

env:
    global:
        - TARGET=test
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: TARGET=cs_dry_run
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        # test 4.4
        - php: 7.4
          env: SYMFONY_VERSION=4.4.*
        # test the latest stable 5.x release
        - php: 7.4
          env: SYMFONY_VERSION=^5.0
        # test the latest release (including beta releases)
        - php: 7.4
          env: DEPENDENCIES=beta

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - make $TARGET

branches:
    only:
        - master
