language: php

sudo: false

dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - deps=high

matrix:
    include:
        - php: hhvm
        - php: 5.4
          env: deps=low
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=low

install:
    - if [ "$deps" = "low" ]; then composer update --prefer-dist --prefer-lowest; fi;
    - if [ "$deps" != "low" ]; then composer update --prefer-dist; fi;

script:
    - make test
